// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnrSGUGOk1S8EddOcerbaGTHW1_LuECfc',
    appId: '1:69606375866:web:1df5975ff99284696add83',
    messagingSenderId: '69606375866',
    projectId: 'raw-nuts-classification',
    authDomain: 'raw-nuts-classification.firebaseapp.com',
    storageBucket: 'raw-nuts-classification.firebasestorage.app',
    measurementId: 'G-28TCYXEP4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsuLkKqbCvy1QFUQD-UprZ1TbO2M1ZwW8',
    appId: '1:69606375866:android:822d562902ebfe226add83',
    messagingSenderId: '69606375866',
    projectId: 'raw-nuts-classification',
    storageBucket: 'raw-nuts-classification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDui6EkuDjXyibWUjTvuvNLFF-25ORc5HU',
    appId: '1:69606375866:ios:f652c6c9ba4a2b076add83',
    messagingSenderId: '69606375866',
    projectId: 'raw-nuts-classification',
    storageBucket: 'raw-nuts-classification.firebasestorage.app',
    iosBundleId: 'com.example.rawNutsClassification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDui6EkuDjXyibWUjTvuvNLFF-25ORc5HU',
    appId: '1:69606375866:ios:f652c6c9ba4a2b076add83',
    messagingSenderId: '69606375866',
    projectId: 'raw-nuts-classification',
    storageBucket: 'raw-nuts-classification.firebasestorage.app',
    iosBundleId: 'com.example.rawNutsClassification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnrSGUGOk1S8EddOcerbaGTHW1_LuECfc',
    appId: '1:69606375866:web:7a8624660da8c5fb6add83',
    messagingSenderId: '69606375866',
    projectId: 'raw-nuts-classification',
    authDomain: 'raw-nuts-classification.firebaseapp.com',
    storageBucket: 'raw-nuts-classification.firebasestorage.app',
    measurementId: 'G-T9GPFGH1G8',
  );
}
